name: Publier une nouvelle version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        
      - name: Configuration de Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Installation des dépendances
        run: |
          npm install
          
      - name: Build Tauri
        run: |
          npm run tauri build
          
      - name: Obtenir la date
        id: date
        run: |
          echo "date=$(Get-Date -Format 'yyyy-MM-dd')" >> $env:GITHUB_OUTPUT
          
      - name: Préparer le répertoire de release
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag.TrimStart("v")
          $releaseDir = "releases/$tag"
          
          # Créer le répertoire de release
          New-Item -Path $releaseDir -ItemType Directory -Force
          
          # Copier les installateurs MSI et EXE
          Copy-Item "src-tauri/target/release/bundle/msi/*.msi" "$releaseDir/windows-admin-tool-$version.msi"
          Copy-Item "src-tauri/target/release/bundle/nsis/*.exe" "$releaseDir/windows-admin-tool-$version-setup.exe"
          
      - name: Mettre à jour version.json
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag.TrimStart("v")
          
          # Créer ou mettre à jour le fichier version.json
          $versionData = @{
            version = $version
            url = "https://github.com/${{ github.repository }}/releases/download/$tag/windows-admin-tool-$version-setup.exe"
            release_date = "${{ steps.date.outputs.date }}"
            description = "Nouvelle version $version de l'outil d'administration Windows"
            is_critical = $false
            size_mb = (Get-Item "releases/$tag/windows-admin-tool-$version-setup.exe").Length / 1MB
            changes = @(
              "Amélioration du système de mise à jour via GitHub"
              "Corrections de bugs et optimisations de performance"
              "Support complet de PowerShell pour les mises à jour sur Windows"
            )
          }
          
          # Convertir et écrire dans version.json
          $versionData | ConvertTo-Json -Depth 4 | Set-Content "version.json"
          
      - name: Créer la Release GitHub
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/${{ github.ref_name }}/*
            version.json
          body: |
            # Version ${{ github.ref_name }}
            
            Date de sortie: ${{ steps.date.outputs.date }}
            
            ## Nouveautés
            - Système de mise à jour entièrement intégré avec GitHub
            - Meilleure compatibilité Windows avec PowerShell
            - Correction du serveur HTTP local remplacé par les appels Tauri natifs
            - Support des mises à jour automatiques
            
            ## Installation
            Téléchargez l'un des fichiers suivants et exécutez-le pour installer ou mettre à jour l'application :
            - L'installeur MSI (installation traditionnelle)
            - L'installeur EXE (installation rapide)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 